// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: PushSendMsgService.proto

package server

import (
	"context"

	"task_Project/rpc/PushSendMsgService/internal/logic"
	"task_Project/rpc/PushSendMsgService/internal/svc"
	"task_Project/rpc/PushSendMsgService/pushSendMsgService"
)

type PushSendMsgServiceServer struct {
	svcCtx *svc.ServiceContext
	pushSendMsgService.UnimplementedPushSendMsgServiceServer
}

func NewPushSendMsgServiceServer(svcCtx *svc.ServiceContext) *PushSendMsgServiceServer {
	return &PushSendMsgServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PushSendMsgServiceServer) Ping(ctx context.Context, in *pushSendMsgService.Request) (*pushSendMsgService.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
