// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: PushSendMsgService.proto

package pushsendmsgserviceclient

import (
	"context"

	"task_Project/rpc/PushSendMsgService/pushSendMsgService"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = pushSendMsgService.Request
	Response = pushSendMsgService.Response

	PushSendMsgService interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultPushSendMsgService struct {
		cli zrpc.Client
	}
)

func NewPushSendMsgService(cli zrpc.Client) PushSendMsgService {
	return &defaultPushSendMsgService{
		cli: cli,
	}
}

func (m *defaultPushSendMsgService) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pushSendMsgService.NewPushSendMsgServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
