// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package core

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	companyFieldNames          = builder.RawFieldNames(&Company{})
	companyRows                = strings.Join(companyFieldNames, ",")
	companyRowsExpectAutoSet   = strings.Join(stringx.Remove(companyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	companyRowsWithPlaceHolder = strings.Join(stringx.Remove(companyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	companyModel interface {
		Insert(ctx context.Context, data *Company) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Company, error)
		FindOneByName(ctx context.Context, name string) (*Company, error)
		Update(ctx context.Context, data *Company) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCompanyModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Company struct {
		Id        int64          `db:"id"`
		Name      string         `db:"name"`
		Domain    sql.NullString `db:"domain"`
		Status    int64          `db:"status"`
		CreatedAt time.Time      `db:"created_at"`
		UpdatedAt time.Time      `db:"updated_at"`
	}
)

func newCompanyModel(conn sqlx.SqlConn) *defaultCompanyModel {
	return &defaultCompanyModel{
		conn:  conn,
		table: "`company`",
	}
}

func (m *defaultCompanyModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCompanyModel) FindOne(ctx context.Context, id int64) (*Company, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", companyRows, m.table)
	var resp Company
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCompanyModel) FindOneByName(ctx context.Context, name string) (*Company, error) {
	var resp Company
	query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", companyRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, name)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCompanyModel) Insert(ctx context.Context, data *Company) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, companyRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Domain, data.Status)
	return ret, err
}

func (m *defaultCompanyModel) Update(ctx context.Context, newData *Company) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, companyRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.Domain, newData.Status, newData.Id)
	return err
}

func (m *defaultCompanyModel) tableName() string {
	return m.table
}
