// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ActionResp struct {
	Success bool
	Message string
}

type Candidate struct {
	User_id   int64
	Score     int64
	Reasons   []string
	Conflicts []string
}

type Company struct {
	Id         int64
	Name       string
	Domain     string
	Status     int64
	Created_at string
	Updated_at string
}

type CompanyCreateReq struct {
	Name   string
	Domain string
}

type CompanyJoinApprovalReq struct {
	Join_user_id int64
	Approve      bool
	Reason       string
}

type CompanyJoinReq struct {
	Company_id    int64
	Department_id int64
	Account       string
	Name          string
	Email         string
	Password      string
}

type CompanyListResp struct {
	List  []Company
	Total int64
}

type CompanyUpdateReq struct {
	Id     int64
	Name   string
	Domain string
	Status int64
}

type Department struct {
	Id         int64
	Company_id int64
	Name       string
	Parent_id  int64
	Status     int64
	Created_at string
	Updated_at string
}

type DepartmentCreateReq struct {
	Company_id int64
	Name       string
	Parent_id  int64
}

type DepartmentListResp struct {
	List  []Department
	Total int64
}

type DepartmentUpdateReq struct {
	Id         int64
	Company_id int64
	Name       string
	Parent_id  int64
	Status     int64
}

type DispatchConfirmReq struct {
	Task_id           int64
	Node_key          string
	Assignee_user_ids []int64
}

type DispatchPreviewReq struct {
	Task_id        int64
	Node_key       string
	Required_tags  []string
	Max_candidates int64
}

type DispatchPreviewResp struct {
	Candidates []Candidate
}

type DispatchReq struct {
	Task_id         int64
	Node_key        string
	Required_tags   []string
	Prefer_user_ids []int64
}

type Empty struct {
}

type HandoverActionReq struct {
	Handover_id int64
	Comment     string
}

type HandoverItem struct {
	Id           int64
	Task_id      int64
	Node_key     string
	From_user_id int64
	To_user_id   int64
	Status       string
	Created_at   string
}

type HandoverListResp struct {
	List  []HandoverItem
	Total int64
}

type HandoverProposeReq struct {
	From_user_id int64
	To_user_id   int64
	Task_id      int64
	Node_key     string
	Reason       string
}

type HandoverReq struct {
	From_user_id int64
	To_user_id   int64
	Task_id      int64
	Node_key     string
	Reason       string
	When         string
}

type IdReq struct {
	Id int64
}

type LogCreateReq struct {
	Company_id            int64
	Task_id               int64
	Node_key              string
	User_id               int64
	Collaborator_user_ids []int64
	Progress_percent      int64
	Report_note           string
	Status                int64
	Deadline_at           string
}

type LogListResp struct {
	List  []UserTaskLog
	Total int64
}

type LogUpdateReq struct {
	Id                    int64
	Collaborator_user_ids []int64
	Progress_percent      int64
	Report_note           string
	Status                int64
	Deadline_at           string
	Is_active             bool
}

type LoginReq struct {
	Account  string
	Password string
}

type LoginResp struct {
	Token string
	User  UserAccount
}

type Notification struct {
	Id         int64
	Category   string
	Title      string
	Content    string
	User_id    int64
	Read       bool
	Created_at string
}

type NotificationAckReq struct {
	Id int64
}

type NotificationListResp struct {
	List  []Notification
	Total int64
}

type OkResp struct {
	Ok bool
}

type PageReq struct {
	Page int64
	Size int64
}

type RegisterReq struct {
	Company_id    int64
	Department_id int64
	Account       string
	Name          string
	Email         string
	Password      string
}

type ScheduleQueryReq struct {
	User_id       int64
	Company_id    int64
	Department_id int64
	Granularity   string
	Start         string
	End           string
}

type Task struct {
	Id                   int64
	Company_id           int64
	Department_id        int64
	Title                string
	Description          string
	Attachments_url      string
	Owner_user_ids       []int64
	Node_user_ids        []int64
	Flow_assignees       map[string][]int64
	Priority             int64
	Start_date           string
	Due_date             string
	Schedule_granularity string
	Status               int64
	Handover_required    bool
	Created_by           int64
	Created_at           string
	Updated_at           string
}

type TaskCreateReq struct {
	Company_id           int64
	Department_id        int64
	Title                string
	Description          string
	Attachments_url      string
	Owner_user_ids       []int64
	Node_user_ids        []int64
	Flow_assignees       map[string][]int64
	Priority             int64
	Start_date           string
	Due_date             string
	Schedule_granularity string
}

type TaskListResp struct {
	List  []Task
	Total int64
}

type TaskUpdateReq struct {
	Id             int64
	Title          string
	Description    string
	Owner_user_ids []int64
	Node_user_ids  []int64
	Flow_assignees map[string][]int64
	Priority       int64
	Status         int64
}

type UserAccount struct {
	Id            int64
	Company_id    int64
	Department_id int64
	Account       string
	Name          string
	Email         string
	Role_tags     []string
	Status        int64
	Hired_at      string
	Left_at       string
	Created_at    string
	Updated_at    string
}

type UserCreateReq struct {
	Company_id    int64
	Department_id int64
	Account       string
	Name          string
	Email         string
	Role_tags     []string
}

type UserListResp struct {
	List  []UserAccount
	Total int64
}

type UserResignReq struct {
	Id      int64
	Left_at string
	Reason  string
}

type UserTaskLog struct {
	Id                    int64
	Company_id            int64
	Task_id               int64
	Node_key              string
	User_id               int64
	Collaborator_user_ids []int64
	Progress_percent      int64
	Report_note           string
	Status                int64
	Deadline_at           string
	Handover_id           int64
	Is_active             bool
	Created_at            string
	Updated_at            string
}

type UserUpdateReq struct {
	Id            int64
	Department_id int64
	Name          string
	Email         string
	Role_tags     []string
	Status        int64
}
