// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: PushSendMsgService.proto

package pushSendMsgService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushSendMsgService_Ping_FullMethodName = "/pushSendMsgService.PushSendMsgService/Ping"
)

// PushSendMsgServiceClient is the client API for PushSendMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushSendMsgServiceClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type pushSendMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushSendMsgServiceClient(cc grpc.ClientConnInterface) PushSendMsgServiceClient {
	return &pushSendMsgServiceClient{cc}
}

func (c *pushSendMsgServiceClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, PushSendMsgService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushSendMsgServiceServer is the server API for PushSendMsgService service.
// All implementations must embed UnimplementedPushSendMsgServiceServer
// for forward compatibility.
type PushSendMsgServiceServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPushSendMsgServiceServer()
}

// UnimplementedPushSendMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushSendMsgServiceServer struct{}

func (UnimplementedPushSendMsgServiceServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPushSendMsgServiceServer) mustEmbedUnimplementedPushSendMsgServiceServer() {}
func (UnimplementedPushSendMsgServiceServer) testEmbeddedByValue()                            {}

// UnsafePushSendMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushSendMsgServiceServer will
// result in compilation errors.
type UnsafePushSendMsgServiceServer interface {
	mustEmbedUnimplementedPushSendMsgServiceServer()
}

func RegisterPushSendMsgServiceServer(s grpc.ServiceRegistrar, srv PushSendMsgServiceServer) {
	// If the following call pancis, it indicates UnimplementedPushSendMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushSendMsgService_ServiceDesc, srv)
}

func _PushSendMsgService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushSendMsgServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PushSendMsgService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushSendMsgServiceServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PushSendMsgService_ServiceDesc is the grpc.ServiceDesc for PushSendMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushSendMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pushSendMsgService.PushSendMsgService",
	HandlerType: (*PushSendMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PushSendMsgService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "PushSendMsgService.proto",
}
